### ISSUE TITLE
Problem with GPIO.

### ISSUE THREAD

**Issue by antun008** [JanuszBedkowski/mandeye_controller#13]
When I following instructions for installing the Mandeye Controller, encountered the following problem:
![WhatsApp Slika 2024-04-16 u 10 01 00_13a910cf](https://github.com/JanuszBedkowski/mandeye_controller/assets/49721808/a9e896e8-50cc-4527-9605-010083db2d60)

Best Regards,
Antun Jakopec

**Comment by JanuszBedkowski** [comment]
We are working on it, it seams that new operating systems requires new GPIO lib.

**Comment by michalpelka** [comment]
Problem is caused by using Raspbian Bookworm - the used GPIO lib does not support that distribution.

**Comment by michalpelka** [comment]
The similar issue : https://github.com/raspberrypi/linux/issues/6037

**Comment by michalpelka** [comment]
I think that we removed the library supporting GPIO and wrote simple implementation instead

**Comment by michalpelka** [comment]
GPIOD was introduced to main, it should be resolved.
