### ISSUE TITLE
Problem with wiring connection BlueLed/ContinuosScan

### ISSUE THREAD

**Issue by GeomPozzoli** [JanuszBedkowski/mandeye_controller#18]
Hi Janusz, congratulations on the project,
I wanted to report the presence of a possible problem in the wire connections page.

If I connect the BlueLed on GPIO06 and the Button1 in GPIO00 as per the table (wiring.md), the button1 for Continuos scan does not work even when trying the "button_demo" test.

The gpios.cpp code states the following:

```
m_buttons[BUTTON::BUTTON_STOP_SCAN] = std::make_unique<PushButton>(5, GPIO::GPIO_PULL::UP);
m_buttons[BUTTON::BUTTON_CONTINOUS_SCANNING] = std::make_unique<PushButton>(6, GPIO::GPIO_PULL::UP);
```

At first I thought that the images had not been updated, but I reversed the connection between button1 and blueled and everything works, so I guess there is a typo in the table.

Is it correct to connect the blueled on GPIO00 or should it actually be connected somewhere else?

Sorry for the bad english

Good day,
Stefano

**Comment by michalpelka** [comment]
Hello @GeomPozzoli you are right, doc is wrong,
According to code:
LED_GPIO_STOP_SCAN - GPIO26
LED_GPIO_COPY_DATA - GPIO19
LED_GPIO_CONTINOUS_SCANNING - GPIO13

BUTTON_STOP_SCAN - GPIO5
BUTTON_CONTINOUS_SCANNING - GPIO6

**Comment by michalpelka** [comment]
The blue led is power and connected to 3.3V

**Comment by GeomPozzoli** [comment]
thanks for the info ed code update

**Comment by michalpelka** [comment]
thanks @GeomPozzoli for closing issue!
