### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by JoLichtenfeld** [JanuszBedkowski/mandeye_controller#21]
Hello,

thanks a lot for open-sourcing this great project.
I could not find any information on the power supply you use. Is it a LiPo? Any recommendations?

Thanks

**Comment by JanuszBedkowski** [comment]
I start with DJI RONIN BG37  https://store.dji.com/pl/product/ronin-s-bg37-grip?vid=47111 
now I am using BG30 https://www.mediaexpert.pl/foto-i-kamery/gimbale/uchwyt-z-akumulatorem-dji-bg30-r-do-gimbala-ronin-s-2-ronin-sc-2-czarny?msockid=2274034eb508625b28821184b4c46350

**Comment by michalpelka** [comment]
You can use any battery pack that is around 12 volts.
Feel free to grab https://cad.onshape.com/documents/a6c6019ccb399ad39d830fad/w/0440af658555626c8fea1136/e/e1bf637894052d9247ac984d?renderMode=0&uiState=651c527c78128a19b84b4be1 and contribute custom battery integration!

**Comment by JoLichtenfeld** [comment]
Thanks for the replies!

**Comment by RomanStadlhuber** [comment]
Are you able to provide an adapted design for the DJI BG30 grip?
The original one only works with BG37 which does not have that extrusion next to the power pins.

Kind regards!

**Comment by JanuszBedkowski** [comment]
Please check if https://github.com/107-systems/T07/pull/1 is helpfull

**Comment by RomanStadlhuber** [comment]
Hello @michalpelka, very nice design, thank you so much!
I will print and try to mount it this week. About the video, sure I can review it.

**Comment by michalpelka** [comment]
@RomanStadlhuber I encourage to review design not a video :).

**Comment by RomanStadlhuber** [comment]
Hello @michalpelka sorry for the late reply. The parts fit nicely onto the BG30 but I have not had the opportunity to test it with the electronics as the pogo pins I ordered have not arrived yet.
Thank you for the design!

**Comment by JanuszBedkowski** [comment]
I have never tested such setup. It requires special power converter since RPi5 is much more powerfull compared with RPi4.
