### ISSUE TITLE
Purpose of picamera2 Support - HDMapping Integration?

### ISSUE THREAD

**Issue by MattiasTancred** [JanuszBedkowski/mandeye_controller#25]
Hi!

First, thank you for creating such a well-thought-out repository and for sharing it as open source — it’s greatly appreciated!

I haven’t fully explored the entire HDMapping repo yet, so I might have missed some details. I’m curious about the purpose of adding picamera2 support. Is it intended to automate the colorization of the point cloud in HDMapping, or does it serve another specific function?

Thanks in advance!

**Comment by JanuszBedkowski** [comment]
Some end-users would like to have additional photos during inspection.
This camera is making shots each 1s, thus it will be easier to orient in point cloud.
We will explore more functionalities if we have time:)

**Comment by MattiasTancred** [comment]
I understand, and that makes sense.

Integrating a 360 camera supported by Raspberry Pi 4 and/or 5, allowing the user to set time intervals, and exporting files along with a CSV containing image names and corresponding XYZ coordinates would be highly useful for this end-user :) 

Again - great work.

**Comment by MattiasTancred** [comment]
Hello again @JanuszBedkowski.

I have added a button to the Mandeye controller that operates the Theta Z1 camera. When pressed, this button captures a 360° image and saves it in the /360 directory within the output folder, alongside the associated LiDAR/GNSS/IMU data. The LiDAR timestamp recorded at the time of the button press is saved as a .txt file in the same directory. My goal is not to colorize the final output .laz. Instead, my goal is to use this for documentation purposes.

My question is: How can I use this recorded timestamp to extract the corresponding XYZ position from the final odometry output in HDMapping? Could you provide guidance or a hint on how to approach this?

Happy New Year! 😊

![theta](https://github.com/user-attachments/assets/eacb3719-ee03-4ba6-bf66-a3531a35bd3f)

**Comment by JanuszBedkowski** [comment]
Can You share this project --> so we can integrate it.

In multi_view_tls_registration_step_2.exe You have plenty of buttons for trajectory export.
Please use 'save all marked trajectories to csv ...'

**Comment by MattiasTancred** [comment]
@JanuszBedkowski - I have added you as a collaborator to my fork of this repository. Please feel free to review my solution and see if it can be integrated.
